### ISSUE TITLE
Deepai doesn't work

### ISSUE THREAD

**Issue by wioniqle-q** [deepai-org/deepai-js-client#23]
![image](https://user-images.githubusercontent.com/69215407/126040731-c5664c93-5544-4d0c-8dc2-0f67c8cee264.png)

const deepai = require('deepai');
deepai.setApiKey(`MY DEEP APİ`);
```
if(message.attachments.first()){
      const image = message.attachments.first().url
      
      let response = await deepai.callStandardApi("nsfw-detector", {
        image:image,
      })
      
      const score = response.output.nsfw_score
      if(score + .2 >= .5){
        message.delete()
        message.channel.send('NO NSFW Images allowed')
      }
    }
```` 

Version:     "deepai": "^1.0.2" ,     "deepai": "^1.0.17"

**Comment by vettorazi** [comment]
@wioniqle-q how did you fixed? having same code 401 over here

**Comment by wioniqle-q** [comment]
> @wioniqle-q how did you fixed? having same code 401 over here

I'm not fixed it. I'm done for this ;) I'm not   using anymore

**Comment by wioniqle-q** [comment]
> @wioniqle-q how did you fixed? having same code 401 over here

That error not you're problem. Deep API is deprecated i think. Still not using ...

**Comment by deepai-org** [comment]
Which API are you using? Most of our APIs are definitely not deprecated.

**Comment by wioniqle-q** [comment]
> Which API are you using? Most of our APIs are definitely not deprecated.

Yeah but I'm saying I don't know :)

**Comment by vettorazi** [comment]
I tried, copying the example code from the website, for Stable Diffusion and the text2img (https://deepai.org/machine-learning-model/text2img)
neither worked and I got the same 401 error code. I suspect that or the API key that the example generated is wrong it's not valid or that I need to pay at least 5 dollars to test it. If this is the case you deepai should have signed in some point

**Comment by wioniqle-q** [comment]
> I tried, copying the example code from the website, for Stable Diffusion and the text2img (https://deepai.org/machine-learning-model/text2img)
> neither worked and I got the same 401 error code. I suspect that or the API key that the example generated is wrong it's not valid or that I need to pay at least 5 dollars to test it. If this is the case you deepai should have signed in some point

Yeah same point 👉☝️
