### ISSUE TITLE
I get error

### ISSUE THREAD

**Issue by jamieduk** [deepai-org/deepai-js-client#24]
Source map error: Error: request failed with status 404
Resource URL: https://cdnjs.deepai.org/deepai.min.js
Source Map URL: deepai.min.map

why cant you design code so it just works out of the box preferably php code or js example that actually works all i get is fkin errors!

**Comment by ojotoxy** [comment]
Can you share what you tried to do which caused this error?

That particular URL doesn't cause a 404 from over here.

**Comment by Sly-Little-Fox** [comment]
That's not an error. That's a warning from the browser. It doesn't break anything.
