### ISSUE TITLE
npm install error

### ISSUE THREAD

**Issue by jamieduk** [deepai-org/deepai-js-client#25]
npm install --save deepai
npm WARN npm npm does not support Node.js v8.10.0
npm WARN npm You should probably upgrade to a newer version of node as we
npm WARN npm can't make any promises that npm will work with this version.
npm WARN npm You can find the latest version at https://nodejs.org/
npm ERR! URL is not defined

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-08-01T14_17_03_094Z-debug.log
root@jnet:/var/www/html/apps/Photo_To_Cartoon#

**Comment by harshagihan** [comment]
npm i deepai
