### ISSUE TITLE
Specify scale factor in the Standard Api

### ISSUE THREAD

**Issue by lokeshn011101** [deepai-org/deepai-js-client#33]
Does anyone know how to specify the upscale factor for an image in the Standard Api?

**Comment by wassienabe** [comment]
> Does anyone know how to specify the upscale factor for an image in the Standard Api?

Did you ever figure this out?

**Comment by lokeshn011101** [comment]
No.

**Comment by DJStompZone** [comment]
As of the current version, the ability to specify the upscale factor for an image in the Standard API is not supported. If this is a feature you'd like to see in the future, please consider creating a feature request, and we'll take it into consideration for future updates.

Thanks for using our platform, and please let us know if you have any further questions or suggestions.
