### ISSUE TITLE
Error: Data after transformation must be a string, an ArrayBuffer, a Buffer, or a Stream

### ISSUE THREAD

**Issue by aymenitc** [deepai-org/deepai-js-client#40]
I'm getting this error on newly installed Ubuntu vps.
It is working fine on my old server 
The error:
`Data after transformation must be a string, an ArrayBuffer, a Buffer, or a Stream`

My code:
```
const filename = `./media/colori.jpg`
var resp = await deepai.callStandardApi("colorizer", {
                          image: fs.createReadStream(filename),
                      })
                         console.log(resp)
```

**Comment by aymenitc** [comment]
I downgraded node from 19.0.1 to 16.17.0 and it works 💯❤️

**Comment by andreisuharew** [comment]
Does anybody know when will it be available for the NodeJS version which supports modules? 
I did the whole project around it and would be a nightmare to rewrite all of it just because of one lib. Version 16.17.0 - seems to work fine - but it's quite a big step back...
Thanks in advance

**Comment by deepai-org** [comment]
@andreisuharew  We'll be happy to fix this for you -- we are not JS experts sadly. Can you share some code and how to reproduce the problem and we'll fix it ASAP

**Comment by andreisuharew** [comment]
> I'm getting this error on newly installed Ubuntu vps. It is working fine on my old server The error: `Data after transformation must be a string, an ArrayBuffer, a Buffer, or a Stream`
> 
> My code:
> 
> ```
> const filename = `./media/colori.jpg`
> var resp = await deepai.callStandardApi("colorizer", {
>                           image: fs.createReadStream(filename),
>                       })
>                          console.log(resp)
> ```

i have exactly the same code example just in try catch . I tested node 17 also works fine . In 18 and 19 versions i see error about invalid data - same as in title of this issue

**Comment by Wheezle211** [comment]
> @andreisuharew We'll be happy to fix this for you -- we are actually not JS experts sadly. Can you share some code and how to reproduce the problem and we'll fix it ASAP

You can simply try any of your example JS code on node 18+. Not sure why this is marked as closed since the issue is still very much present and downgrading node is not a solution but a workaround.

**Comment by romw314** [comment]
I don't want to downgrade node, but see this:
https://stackoverflow.com/questions/56803702/axios-error-data-after-transformation-must-be-a-string-an-arraybuffer-a-buffer

**Comment by spejamas** [comment]
Please revisit this issue deepai team, I would love to use one of your endpoints in my application without downgrading node.

The problem is related to how axios handles the FormData type, and some kind of change in that type in node 18. See https://github.com/axios/axios/issues/5327 and https://github.com/axios/axios/pull/5316.

Maybe this is as simple as updating your axios dependency?
