### ISSUE TITLE
User profile page displays 'undefined' in My Likes tab

### ISSUE THREAD

**Issue by J0SAL** [deepai-org/deepai-js-client#52]
![Web capture_13-4-2023_224337_deepai org](https://user-images.githubusercontent.com/52382282/231834903-f6b10393-c286-4ffb-a9f5-28d14985aa21.jpeg)

### Steps to reproduce

1. Create an account using Google Sign In
2. Go to 'My Profile' page
3. Navigate to the 'My Likes' tab

### Expected behavior:
The 'My Likes' tab should display "[username] hasn't Liked anything yet.", if user has not liked any content

### Actual behavior:
The 'My Likes' tab displays "**undefined** hasn't Liked anything yet."

**Comment by deepai-org** [comment]
Thanks for the bug report, this is actually an issue with our website not the JS client.
