### ISSUE TITLE
"image-editor" don't exist in Models type

### ISSUE THREAD

**Issue by Strooss** [deepai-org/deepai-js-client#54]
Please add the "image-editor" to the Models type. as it exists in the deepai [documentation](https://deepai.org/machine-learning-model/image-editor).
![image](https://github.com/deepai-org/deepai-js-client/assets/102289594/4c33c8bd-0b9d-4a76-8df6-721359d98d94)

**Comment by deepai-org** [comment]
This is a real issue, but it's acutally not for this repo, and we didn't create the typescript file ourselves, so we have to close this for now.
